### ISSUE TITLE
Could not sign in and save user in session

### ISSUE THREAD

**Issue by shenoudab** [shenoudab/devise_couch#1]
Dears, 

  kindly, after the user signin successfully he is redirecting back to the sign in page. 
seems that the logged in user not saved in the session as logged in user.

   and i got that Message "Could not sign in user" from the failure_app.rb

please, check and review

**Comment by guivinicius** [comment]
I have this same problem. =/ ... really annoying!

**Comment by shenoudab** [comment]
kindly, try to help in finding the case of that problem with devise.
as we are looking for a help from devise regarding this.

**Comment by guivinicius** [comment]
I'm using this ORM for couch + devise

http://github.com/lucasrenan/CouchRest-Model-ORM-for-Devise

I think this two methods is what is missing for devise_couch

def find_for_authentication(conditions)
          find(:conditions => conditions)
        end

```
    def find(*args)
      options = args.extract_options!
      raise "You can't search with more than one condition yet =(" if options[:conditions].keys.size > 1

      find_by_key_and_value(options[:conditions].keys.first, options[:conditions].values.first)
    end
```

**Comment by shenoudab** [comment]
kindly, devise_couch is now ready for usage. i have commit some changes.
thanks for your share.
