### ISSUE TITLE
Not Compatible with Devise >=2.00

### ISSUE THREAD

**Issue by stonehz** [shenoudab/devise_couch#15]
Schema Incompatible with newer versions:
Problem appears here:
https://github.com/shenoudab/devise_couch/blob/master/lib/devise/orm/couchrest_model/schema.rb#L5

More info can be found here:
https://github.com/plataformatec/devise/wiki/How-To:-Upgrade-to-Devise-2.0-migration-schema-style

**Comment by alexanderedge** [comment]
Is there any chance that this can be added?

**Comment by shenoudab** [comment]
Please, try to fork the project. as there is not maintenance for it in the current time
