### ISSUE TITLE
Cannot create Devise Model

### ISSUE THREAD

**Issue by jawosis** [shenoudab/devise_couch#3]
When running "rails generate couchrest_model:devise User" I get a "no such file to load -- devise/orm/" error.

I guess I have to change the corresponding entry in the initializer but I don't understand this part of the instructions: 
"Make sure to specify either couchrest_model (ActiveModel::Validations) as the orm in the configuration file."
--> What do I have to specify in the initializer file?

**Comment by shenoudab** [comment]
Dear, 

   you have first to set the default ORM of devise, by setting  the require in config/initialize/devise.rb to 'devise/orm/couchrest_model'

also by using my version of couchrest_model http://github.com/shenoudab/couchrest_model
and also add 
gem 'rails3-generators', :git => 'git://github.com/shenoudab/rails3-generators.git'

and then use "rails g devise User" which will generate Devise User Model by Couchrest_Model.
