### ISSUE TITLE
Can only login as first user (in alphabetical order)

### ISSUE THREAD

**Issue by ghost** [shenoudab/devise_couch#6]
I've just switched from MongoDB to CouchDB using CouchRestModel.  I've been trying to fix my login for 12 hours now and so far no success.  I've looked at all the closed tickets and searched the internet for answers but I haven't found anything that helps.

If I login as the first user in alphabetical order, IE "andy", it works fine.  But if I login as another user, IE "phill", it does not allow me to login.  I see the redirect to my dashboard, as it should, then it redirects back to login.

I have confirmed that the find_for_authentication is returning the correct user, but something after that is causing it to fail.  Maybe something in authenticate_user!.

So now I'm asking for help as I can't figure it out.

Thanks.

**Comment by shenoudab** [comment]
Dear Phill, 

 what did you mean in alphabetical order ? and how you create that alphabetical order ?
did you use "email" or "login" as authentication_keys, and what is the steps create this case ?

**Comment by ghost** [comment]
I'm using login as the authentication key.  I added a user and it was fine.  I added another user and I could not login.  After about 10 hours I figured out that the user I could log in as was alphabetically before the one I could not login as.  So I added another account starting with an A for the login.  I was able to login to that account, but then I could not log into the previously working account.

```
def self.find_for_authentication(conditions = {})
  u = User.find_by_login(conditions[:login])
end
```

I've added logging and I see that it's selecting the correct user every time.  That's why I think it's something beyond the custom finder.

Everything is pretty straight forward.  It was working fine with MongoDB.

**Comment by shenoudab** [comment]
try remove the method self.find_for_authentication from your model.
and just use the config/devise.rb file and set authentication_keys = [:login].

**Comment by ghost** [comment]
config.authentication_keys = [ :login ] is already set in the initializer.  I get the same problem with or without the find_for_authentication override.

**Comment by ghost** [comment]
Ah, the CouchDB log gives some hints.  It shows two queries.  First the query after the login screen: 
    1> [info] [<0.1070.3>] 127.0.0.1 - - 'GET' /auction/_design/User/_view/by_login?limit=1&key=%22phill%22&include_docs=true 200
That works fine.  Returns the correct document.  Then it queries again:
    1> [info] [<0.1074.3>] 127.0.0.1 - - 'GET' /auction/_design/User/_view/all?conditions=%7B%3Aid%3D%3E%22phill%22%7D&limit=1&include_docs=true 200
This query returns the first document instead of the id 'phill'.  This second query is the one I can't find in the code where it's being called.  I'm pretty sure it's after the login screen when the next screen is checking for authentication using authenticate_user! in the controllers.

**Comment by shenoudab** [comment]
Dear Phill, 

 i have publish a rails application example for devise using couchdb using my lib devise_couch. github.com/shenoudab/devise_couch_example

i create alot of examples with different email alphabetical and they are working fine.

**Comment by ghost** [comment]
I'm getting closer to the solution.  It's that second query to couchdb that's the problem.  I have no idea where it's being called from yet or why the couchdb URL is wrong.  I'm thinking that I'll have a solution soon.

**Comment by shenoudab** [comment]
i will try to get that specific case, and if i got it i will try to find a solution for it.

**Comment by ghost** [comment]
I spent the whole day yesterday in ruby-debug trying to figure out the problem.  Seems like that 2nd query is coming from Warden somewhere.  But I was unable to find it.

I cloned your example and it seemed to work just fine but it doesn't have a secure area.  So I added a new controller called SecureArea.  In that controller I added the before filter authenticate_user!  The index.html.erb was just a simple current_user.inspect.  This is where I get redirected back to the login screen and where my problem is.

Am I doing it wrong?

Terminal
    $ rails g controller SecureArea
    create  app/controllers/secure_area_controller.rb
    create    app/views/secure_area
config/routes.rb
    resources :secure_area
app/controllers/secure_area_controller.rb
    class SecureAreaController < ApplicationController
      before_filter :authenticate_user!
    end
app/views/secure_area/index.html.erb
    Current User: <%= current_user.inspect %>
http://localhost:3000/secure_area
    Works with user "alex"
    Fails with user "bart"

**Comment by shenoudab** [comment]
kindly, then this issue raised in or because of authenticate_user! ?

**Comment by ghost** [comment]
Yes, I believe so.  But it works just fine in MongoDB, that's why I suspect something with devise_couch is the cause.  Or maybe it's Couchrest...

I have not been able to track down where the 2nd document get is sent from.  The whole problem is that it's tacking on some invalid params as noted above: 
    ?conditions={:id=>"username"}

**Comment by ghost** [comment]
Strange new development.  I did a bundle update and it installed a different version of devise.  Now everything seems to be working correctly.

```
Using couchrest_model (1.0.0.beta8) from git://github.com/couchrest/couchrest_model.git (at master) 
Installing devise (1.1.5) 
Using devise_couch (1.0.0.beta2) from git://github.com/shenoudab/devise_couch.git (at master) 
Using orm_adapter (0.0.3) from git://github.com/shenoudab/orm_adapter.git (at master) 
Using rails3-generators (0.12.1) from git://github.com/shenoudab/rails3-generators.git (at master) 
```

So I switched it back to 1.2.rc and I was not able to login anymore.
    Using devise (1.2.rc) 

Switched it back to 1.1.5 and it works.
    Using devise (1.1.5) 

Looks like the bug is actually in the latest version of Devise.

**Comment by shenoudab** [comment]
great for now, but we have to check for the cause with the new version of Devise 1.2.*

**Comment by perezd** [comment]
This seems like a symptom of a bigger systemic bug in orm_adapter.

?conditions= is not a valid CouchDB view parameter, and from what I can tell, you're find_all definition in orm_adapter for couchrest_model is just going to return all, without any filter. Please let me know how I can help you debug this issue.
- Derek

**Comment by perezd** [comment]
upon closer inspection, it appears you've nearly copied and pasted the code from mongoid's orm_adapter file to couchdbs? That will not work. I am going to fork, and attempt to fix.

**Comment by shenoudab** [comment]
hallo, i will dig into orm_adapter the upcoming days, to check the above and enhance.

**Comment by shenoudab** [comment]
hallo Derek, 

kindly,  update to the new published  updates for orm_adaptor and devise_couch_example. which will going to solve the reported problems ... please, check and feed me back.

**Comment by shenoudab** [comment]
kindly,  update to the new published  updates for orm_adaptor and devise_couch_example. which will going to solve the reported problems ... please, check and feed me back.

**Comment by shannonwells** [comment]
Hi I have installed the published updates you noted here.  Unfortunately now, while login works, I cannot create new accounts:

undefined method `by_confirmation_token' for #<CouchRest::Model::Base::OrmAdapter:0x105bff990 @klass=User>

Application Trace | Framework Trace | Full Trace
/Library/Ruby/Gems/1.8/bundler/gems/orm_adapter-dcf9cd38b4fc/lib/orm_adapter/adapters/couchrest_model.rb:43:in `send'
/Library/Ruby/Gems/1.8/bundler/gems/orm_adapter-dcf9cd38b4fc/lib/orm_adapter/adapters/couchrest_model.rb:43:in`find_first'

I have not tracked this issue further.

**Comment by shenoudab** [comment]
kindly, we are currently support :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable for the devise model other devise modules not tested.

please, refer to the devise_couch_test project for a working example.

**Comment by perezd** [comment]
Check out my fork: https://github.com/Orchestra/orm_adapter

I've got token authentication working. The verison I'm using assumes you've setup a basic view_by :some_key, and you want to find any of the conditions as "true", In reality, this is basically a hack, but since only Devise uses this thing, and only really uses it in like 4 places, this suffices for the way they use it.

in sort, orm_adapter is really a dumb idea for something like CouchDB, it just doesn't fit its model.

Enjoy my hack! :D
