### ISSUE TITLE
token_authenticatable not working with devise 1.2.rc

### ISSUE THREAD

**Issue by perezd** [shenoudab/devise_couch#7]
its generating this query to couchdb:

GET /users/_design/User/_view/all?conditions=%7B%3Aauthentication_token%3D%3E%22Seaf8VnDHAv2jmLGYEuSPFoxSBF0bI5sqYxMG4KnyqeOHIaLoNAwBPDZOCwz%22%7D&limit=1&include_docs=true

it should be generating this query:

GET /users/_design/User/_view/by_authentication_token?key=%22xyzfasdasd%22

Any advice? I may investigate and append a patch if I can.

**Comment by perezd** [comment]
I think there is something wrong the way Devise uses the orm_adapter integration for checking things. I patched my local model file with this, and everything works great now:

   def self.authentication_token
       loop do
         token = Devise.friendly_token
         break token if self.view(:by_authentication_token, :key => token).empty?
        end
    end
The area I believe that is causing this problem is within devise itself, check authenticatable.rb with the lib/models directory. L137, the generate_token model appears to use a generic to_adapter call, and its probably not doing what we want it to for couch.

Any suggestions for a proper fix?

**Comment by perezd** [comment]
I am seeing this type of behavior when trying to destroy a user session with logout as well :(

'GET' /users/_design/User/_view/all?conditions=%7B%3Aid%3D%3E%227a7bc79e0c559401aba026fcc49d482c%22%7D&limit=1&include_docs=true

Is this some sort of bigger issue?

**Comment by shenoudab** [comment]
kindly,  update to the new published  updates for orm_adaptor and devise_couch_example. which will going to solve the reported problems ... please, check and feed me back.
